#!/bin/bash
set -ex

DRIVERS="$(ls -d drivers/sqlboiler-* | cut -d- -f2-)"

# main image (all drivers included)
docker build -f "${DOCKERFILE_PATH}" -t sqlboiler .

# single driver images
for driver in $DRIVERS; do
    docker build -f "${DOCKERFILE_PATH}" --target "sqlboiler-${driver}" -t "sqlboiler-${driver}" .
done
